export const INGREDIENTS = [
  { id: "apple", name: "Manzana", image: "/ingredients/apple.png" },
  { id: "cheese", name: "Queso", image: "/ingredients/cheese.png" },
  { id: "fish", name: "Pescado", image: "/ingredients/fish.png" },
  { id: "banana", name: "Banana", image: "/ingredients/banana.png" },
  { id: "beef", name: "Ternera", image: "/ingredients/beef.png" },
  { id: "chicken", name: "Pollo", image: "/ingredients/chicken.png" },
  { id: "egg", name: "Huevo", image: "/ingredients/egg.png" },
  { id: "lettuce", name: "Lechuga", image: "/ingredients/lettuce.png" },
  { id: "onion", name: "Cebolla", image: "/ingredients/onion.png" },
  { id: "tomato", name: "Tomate", image: "/ingredients/tomato.png" },
  { id: "water", name: "Agua", image: "/ingredients/water.png" },
  { id: "milk", name: "Leche", image: "/ingredients/milk.png" },
  { id: "bread", name: "Pan", image: "/ingredients/bread.png" },
  { id: "butter", name: "Mantequilla", image: "/ingredients/butter.png" },
  { id: "salt", name: "Sal", image: "/ingredients/salt.png" },
  { id: "pepper", name: "Pimienta", image: "/ingredients/pepper.png" },
  { id: "sugar", name: "Azúcar", image: "/ingredients/sugar.png" },
  { id: "oil", name: "Aceite", image: "/ingredients/oil.png" },
  { id: "flour", name: "Harina", image: "/ingredients/flour.png" },
  { id: "yogurt", name: "Yogur", image: "/ingredients/yogurt.png" },
  { id: "chocolate", name: "Chocolate", image: "/ingredients/chocolate.png" },
  { id: "coffee", name: "Café", image: "/ingredients/coffee.png" },
  { id: "tea", name: "Té", image: "/ingredients/tea.png" },
  { id: "juice", name: "Zumo", image: "/ingredients/juice.png" },
  { id: "soda", name: "Soda", image: "/ingredients/soda.png" },
  { id: "watermelon", name: "Sandía", image: "/ingredients/watermelon.png" },
  { id: "kiwi", name: "Kiwi", image: "/ingredients/kiwi.png" },
  { id: "pineapple", name: "Piña", image: "/ingredients/pineapple.png" },
  { id: "strawberry", name: "Fresa", image: "/ingredients/strawberry.png" },
  { id: "raspberry", name: "Frambuesa", image: "/ingredients/raspberry.png" },
  { id: "grape", name: "Uva", image: "/ingredients/grape.png" },
  { id: "lemon", name: "Limón", image: "/ingredients/lemon.png" },
  { id: "lime", name: "Lima", image: "/ingredients/lime.png" },
  { id: "orange", name: "Naranja", image: "/ingredients/orange.png" },
  { id: "pear", name: "Pera", image: "/ingredients/pear.png" },
  { id: "peach", name: "Melocotón", image: "/ingredients/peach.png" },
  { id: "cherry", name: "Cereza", image: "/ingredients/cherry.png" },
  { id: "mango", name: "Mango", image: "/ingredients/mango.png" },
  { id: "papaya", name: "Papaya", image: "/ingredients/papaya.png" },
  { id: "brocoli", name: "Brocoli", image: "/ingredients/brocoli.png" },
  { id: "carrot", name: "Zanahoria", image: "/ingredients/carrot.png" },
  { id: "sausache", name: "Salchicha", image: "/ingredients/sausache.png" },
  { id: "ketchup", name: "Ketchup", image: "/ingredients/ketchup.png" },
  { id: "mustard", name: "Mostaza", image: "/ingredients/mustard.png" },
  { id: "mayonnaise", name: "Mayonesa", image: "/ingredients/mayonnaise.png" },
  { id: "vinegar", name: "Vinagre", image: "/ingredients/vinegar.png" },
  { id: "cream", name: "Nata", image: "/ingredients/cream.png" },
  {
    id: "cauliflower",
    name: "Coliflor",
    image: "/ingredients/cauliflower.png",
  },
  { id: "corn", name: "Maíz", image: "/ingredients/corn.png" },
  { id: "cucumber", name: "Pepino", image: "/ingredients/cucumber.png" },
  { id: "eggplant", name: "Berenjena", image: "/ingredients/eggplant.png" },
  { id: "garlic", name: "Ajo", image: "/ingredients/garlic.png" },
  { id: "mushroom", name: "Champiñón", image: "/ingredients/mushroom.png" },
  { id: "pepperoni", name: "Pepperoni", image: "/ingredients/pepperoni.png" },
  { id: "potato", name: "Papa", image: "/ingredients/potato.png" },
  { id: "radish", name: "Remolacha", image: "/ingredients/radish.png" },
  { id: "spinach", name: "Espinaca", image: "/ingredients/spinach.png" },
  { id: "zucchini", name: "Calabacín", image: "/ingredients/zucchini.png" },
  { id: "turkey", name: "Pavo", image: "/ingredients/turkey.png" },
  { id: "rice", name: "Arroz", image: "/ingredients/rice.png" },
  { id: "pasta", name: "Pasta", image: "/ingredients/pasta.png" },
  { id: "lentils", name: "Lentejas", image: "/ingredients/lentils.png" },
  { id: "beans", name: "Alubias", image: "/ingredients/beans.png" },
  { id: "pile of dirt", name: "Montón de tierra", image: "/ingredients/dirt.png" },
  { id: 'screws', name: 'Tornillos', image: '/ingredients/screws.png' },
];
